title: "Julien Romero"
description: "Associate Professor in Computer Science â€“ AI & Machine Learning"
baseurl: ""
url: "https://aunsiels.github.io/personal-website"

markdown: kramdown

# Keep things simple
theme: null

# Build settings
exclude:
  - README.md

